apiVersion: v2
name: app-chart
description: Generic application Helm chart for the k8s-gitops-platform
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Kumar Raja Puvvalla
    url: https://github.com/kumarrajapuvvalla-bit
keywords:
  - devops
  - platform-engineering
  - gitops
